import { Routes } from '@angular/router';

export const routes: Routes = [
  {
    path: '',
    loadComponent: () => import('./layout/default-layout/default-layout.component').then(m => m.DefaultLayoutComponent),
    children: [
      { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
      { path: 'dashboard', loadComponent: () => import('./views/dashboard/dashboard.component').then(m => m.DashboardComponent) },
      { path: 'theme/colors', loadComponent: () => import('./views/theme/colors/colors.component').then(m => m.ColorsComponent) },
      { path: 'theme/typography', loadComponent: () => import('./views/theme/typography/typography.component').then(m => m.TypographyComponent) },
      { path: 'base/accordion', loadComponent: () => import('./views/base/accordion/accordion.component').then(m => m.AccordionComponent) },
      { path: 'base/breadcrumbs', loadComponent: () => import('./views/base/breadcrumbs/breadcrumbs.component').then(m => m.BreadcrumbsComponent) },
      { path: 'base/cards', loadComponent: () => import('./views/base/cards/cards.component').then(m => m.CardsComponent) },
      { path: 'base/carousels', loadComponent: () => import('./views/base/carousels/carousels.component').then(m => m.CarouselsComponent) },
      { path: 'base/collapses', loadComponent: () => import('./views/base/collapses/collapses.component').then(m => m.CollapsesComponent) },
      { path: 'base/list-groups', loadComponent: () => import('./views/base/list-groups/list-groups.component').then(m => m.ListGroupsComponent) },
      { path: 'base/navs', loadComponent: () => import('./views/base/navs/navs.component').then(m => m.NavsComponent) },
      { path: 'base/paginations', loadComponent: () => import('./views/base/paginations/paginations.component').then(m => m.PaginationsComponent) },
      { path: 'base/placeholders', loadComponent: () => import('./views/base/placeholders/placeholders.component').then(m => m.PlaceholdersComponent) },
      { path: 'base/popovers', loadComponent: () => import('./views/base/popovers/popovers.component').then(m => m.PopoversComponent) },
      { path: 'base/progress', loadComponent: () => import('./views/base/progress/progress.component').then(m => m.ProgressComponent) },
      { path: 'base/spinners', loadComponent: () => import('./views/base/spinners/spinners.component').then(m => m.SpinnersComponent) },
      { path: 'base/tabs', loadComponent: () => import('./views/base/tabs/tabs.component').then(m => m.TabsComponent) },
      { path: 'base/tables', loadComponent: () => import('./views/base/tables/tables.component').then(m => m.TablesComponent) },
      { path: 'base/tooltips', loadComponent: () => import('./views/base/tooltips/tooltips.component').then(m => m.TooltipsComponent) },
      { path: 'buttons/buttons', loadComponent: () => import('./views/buttons/buttons/buttons.component').then(m => m.ButtonsComponent) },
      { path: 'buttons/button-groups', loadComponent: () => import('./views/buttons/button-groups/button-groups.component').then(m => m.ButtonGroupsComponent) },
      { path: 'buttons/dropdowns', loadComponent: () => import('./views/buttons/dropdowns/dropdowns.component').then(m => m.DropdownsComponent) },
      { path: 'forms/form-control', loadComponent: () => import('./views/forms/form-control/form-control.component').then(m => m.FormControlComponent) },
      { path: 'forms/select', loadComponent: () => import('./views/forms/select/select.component').then(m => m.SelectComponent) },
      { path: 'forms/checks-radios', loadComponent: () => import('./views/forms/checks-radios/checks-radios.component').then(m => m.ChecksRadiosComponent) },
      { path: 'forms/range', loadComponent: () => import('./views/forms/range/range.component').then(m => m.RangeComponent) },
      { path: 'forms/input-group', loadComponent: () => import('./views/forms/input-group/input-group.component').then(m => m.InputGroupComponent) },
      { path: 'forms/floating-labels', loadComponent: () => import('./views/forms/floating-labels/floating-labels.component').then(m => m.FloatingLabelsComponent) },
      { path: 'forms/layout', loadComponent: () => import('./views/forms/layout/layout.component').then(m => m.LayoutComponent) },
      { path: 'forms/validation', loadComponent: () => import('./views/forms/validation/validation.component').then(m => m.ValidationComponent) },
      { path: 'charts', loadComponent: () => import('./views/charts/charts.component').then(m => m.ChartsComponent) },
      { path: 'icons/coreui-icons', loadComponent: () => import('./views/icons/coreui-icons/coreui-icons.component').then(m => m.CoreuiIconsComponent) },
      { path: 'icons/flags', loadComponent: () => import('./views/icons/flags/flags.component').then(m => m.FlagsComponent) },
      { path: 'icons/brands', loadComponent: () => import('./views/icons/brands/brands.component').then(m => m.BrandsComponent) },
      { path: 'notifications/alerts', loadComponent: () => import('./views/notifications/alerts/alerts.component').then(m => m.AlertsComponent) },
      { path: 'notifications/badges', loadComponent: () => import('./views/notifications/badges/badges.component').then(m => m.BadgesComponent) },
      { path: 'notifications/modals', loadComponent: () => import('./views/notifications/modals/modals.component').then(m => m.ModalsComponent) },
      { path: 'notifications/toasts', loadComponent: () => import('./views/notifications/toasts/toasts.component').then(m => m.ToastsComponent) },
      { path: 'widgets', loadComponent: () => import('./views/widgets/widgets.component').then(m => m.WidgetsComponent) },
    ]
  },
  { path: 'login', loadComponent: () => import('./views/pages/login/login.component').then(m => m.LoginComponent) },
  { path: 'register', loadComponent: () => import('./views/pages/register/register.component').then(m => m.RegisterComponent) },
  { path: '404', loadComponent: () => import('./views/pages/page404/page404.component').then(m => m.Page404Component) },
  { path: '500', loadComponent: () => import('./views/pages/page500/page500.component').then(m => m.Page500Component) },
  { path: '**', redirectTo: '404' }
];
